apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-app
  template:
    metadata:
      labels:
        app: helm-app
    spec:
      containers:
      - name: app
        image: nginx:latest
